In [77]:
import os
import numpy as np
import pandas as pd
from scipy.misc import imread
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import PIL

import tensorflow as tf
import keras
from tensorflow.python.framework import ops
ops.reset_default_graph()


In [78]:
data=pd.read_csv('/Users/pallavi385/Downloads/digitsimages/train.csv')

In [79]:
data.head()

filename  label
0    0.png      4
1    1.png      9
2    2.png      1
3    3.png      7
4    4.png      3

In [80]:
img=imread('/Users/pallavi385/Downloads/digitsimages/images/train/0.png')

/Users/pallavi385/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  """Entry point for launching an IPython kernel.


In [81]:
img0=PIL.Image.open('/Users/pallavi385/Downloads/digitsimages/images/train/0.png')

In [82]:
img0

In [83]:
temp = []
for img_name in data.filename:
    #print(img_name)
    img = imread('/Users/pallavi385/Downloads/digitsimages/images/train/'+img_name, flatten=True)
    img = img.astype('float32')
    temp.append(img)
    
train_x = np.stack(temp)

train_x /= 255.0
train_x = train_x.reshape(-1, 784).astype('float32')


/Users/pallavi385/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  after removing the cwd from sys.path.


In [84]:
train_x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [85]:
test_data=pd.read_csv('/Users/pallavi385/Downloads/test_digit.csv')

In [86]:
test_data.head()

filename
0  49000.png
1  49001.png
2  49002.png
3  49003.png
4  49004.png

In [87]:
temp = []
for img_name in test_data.filename:
    #print(img_name)
    img = imread('/Users/pallavi385/Downloads/digitsimages/images/test/'+img_name, flatten=True)
    img = img.astype('float32')
    temp.append(img)
    
test_x = np.stack(temp)

test_x /= 255.0
test_x = test_x.reshape(-1, 784).astype('float32')

/Users/pallavi385/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  after removing the cwd from sys.path.


In [88]:
test_x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [89]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49000 entries, 0 to 48999
Data columns (total 2 columns):
filename    49000 non-null object
label       49000 non-null int64
dtypes: int64(1), object(1)
memory usage: 765.7+ KB


In [90]:
train_y=keras.utils.np_utils.to_categorical(data.label.values)

In [91]:
data.label.values

array([4, 9, 1, ..., 9, 3, 0])

In [92]:
split_size=int(train_x.shape[0]*0.7)

In [93]:
train_x,val_x=train_x[:split_size],train_x[split_size:]

In [94]:
train_y,val_y=train_y[:split_size],train_y[split_size:]

In [95]:
data.label.ix[split_size:]

/Users/pallavi385/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


34300    3
34301    1
34302    6
34303    8
34304    3
34305    8
34306    8
34307    9
34308    3
34309    8
34310    4
34311    6
34312    6
34313    3
34314    6
34315    7
34316    5
34317    3
34318    0
34319    3
34320    9
34321    3
34322    8
34323    8
34324    7
34325    4
34326    3
34327    8
34328    6
34329    5
        ..
48970    7
48971    5
48972    0
48973    1
48974    4
48975    1
48976    7
48977    5
48978    6
48979    5
48980    6
48981    3
48982    5
48983    5
48984    9
48985    2
48986    9
48987    0
48988    0
48989    7
48990    0
48991    1
48992    1
48993    6
48994    9
48995    2
48996    4
48997    9
48998    3
48999    0
Name: label, Length: 14700, dtype: int64

In [96]:
data.shape

(49000, 2)

In [97]:
train_x.shape

(34300, 784)

In [98]:
test_x.shape

(21000, 784)

In [99]:
split_size

34300

In [100]:
input_num_units = 784
hidden_num_units = 50
output_num_units = 10
epochs = 5
batch_size = 128


In [111]:
from tensorflow.keras.models import Sequential

In [112]:
from tensorflow.keras.layers import Dense

In [113]:
from tensorflow.python.framework import ops
ops.reset_default_graph()

In [121]:
model = Sequential([
  Dense(units=hidden_num_units, input_dim=input_num_units, activation='relu'),
  Dense(units=output_num_units, input_dim=hidden_num_units, activation='softmax'),
])


In [122]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [123]:
trained_model = model.fit(train_x, train_y, nb_epoch=epochs, batch_size=batch_size, validation_data=(val_x, val_y))


W0522 14:26:33.054965 4635395520 training.py:686] The `nb_epoch` argument in `fit` has been renamed `epochs`.


Train on 34300 samples, validate on 14700 samples
Epoch 1/5
34300/34300 [==============================] - 2s 45us/sample - loss: 0.5494 - accuracy: 0.8596 - val_loss: 0.3104 - val_accuracy: 0.9141
Epoch 2/5
34300/34300 [==============================] - 1s 23us/sample - loss: 0.2591 - accuracy: 0.9278 - val_loss: 0.2482 - val_accuracy: 0.9307
Epoch 3/5
34300/34300 [==============================] - 1s 26us/sample - loss: 0.2123 - accuracy: 0.9402 - val_loss: 0.2193 - val_accuracy: 0.9403
Epoch 4/5
34300/34300 [==============================] - 1s 28us/sample - loss: 0.1813 - accuracy: 0.9489 - val_loss: 0.1941 - val_accuracy: 0.9473
Epoch 5/5
34300/34300 [==============================] - 1s 24us/sample - loss: 0.1578 - accuracy: 0.9546 - val_loss: 0.1770 - val_accuracy: 0.9507


In [124]:
pred = model.predict_classes(test_x)

In [126]:
pred

array([4, 0, 9, ..., 6, 6, 2])